### ISSUE TITLE
References to original project on node page

### ISSUE THREAD

**Issue by buffet-time** [silverspectro/vue-clickaway2#2]
In https://npm.runkit.com/vue-clickaway2 you can see it still is pointing back to the original version,

Also you might want to remove the "From CDN, chose the one you prefer: Only available for version 2.2.2" part seeing as it no longer really applies. And just look through the npm package and through the documentation in the repo to make sure everything is pointing towards vue-clickaway2 not the original.

**Comment by buffet-time** [comment]
I fixed the things i saw in README.md but i think the npm.runkit.com stuff is on the npm site itself so i cant fix that.

**Comment by silverspectro** [comment]
I use the npm package in multiple projects, and it seems to be the good one with all the last modifications, so i don't understand what you are pointing at with the npm runkit example.
And yes, the CDN version should be maintained or deleted, but it is still available on the url for the ulterior version.

**Comment by buffet-time** [comment]
Yesterday i guess it just took longer than usual for it to update? it was showing 2.2.3 instead of 3 a few hours after you updated the package. Also I think it's important in my merge request the imports because you need to import from vue-clickaway2 which some people may realize but for a readme purpose and how people often scroll past just to see the code it's important that it's updated.
